# Setup
title:        Colony Evolver
tagline:      exploring generative growth and evolution
projecturl: https://github.com/jlopezbi/ColonyEvolver
url:      ""
baseurl: "/ColonyEvolver"
#home: https://jlopezbi.github.io/ColonyEvolver/
paginate:     5

# About/contact
author:
  name:       Josh Lopez-Binder
  url:        http://joshlopezbinder.com/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
