# Setup
title:        Colony Evolver
tagline:      exploring generative growth and evolution
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Josh Lopez-Binder
  url:        http://joshlopezbinder.com/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
